# Generated by Django 5.2 on 2025-04-22 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='qr_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
