# Generated by Django 5.2 on 2025-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='qr_code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
